scala_library(
    name = "zh",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = require(
        "data/references",
        "models/corenlp",
        "models/local",
        "util"
    ),
)
