scala_library(
    name = "patterns",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = require(
      "constants",
      "data/patterns/zh",
      "models/local",
    ),
)
