scala_library(
    name = "agents",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = require(
        "@edu_stanford_nlp_stanford_corenlp",
        "clients",
        "data/patterns",
        "models/local",
        "models/corenlp",
        "util"
    )
)